In [1]:
# What you've seen before
import requests
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
% matplotlib inline

# What's new
from bs4 import BeautifulSoup # We'll be using this to scrape through HTML documents
import re # We'll be using regular expressions (a bit) to search through text
import networkx as nx # We'll be using this to graph a website (not super important)

In [2]:
def subreddit_scraper(url):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'}
    html_doc = requests.get(url,headers=headers).text
    soup = BeautifulSoup(html_doc, "html5lib")
    content = []
    for tagline in soup.find_all('p',{'class':'tagline'}):
        #for writer in tagline('a',{'class':'author'}):
         #   print(writer)
        temp = tagline.find('a',{'class':'author'})
        if temp != None :
            author = temp.string
        temp = tagline.find('span',{'class':'unvoted'})
        point = 0
        if temp != None :
            point = temp.string.split()[0]
        time = tagline.find('time').string
    
        content.append({
            'name':author,
            'points':point,
            'time':time
        })
    content_df = pd.DataFrame(content)
    return content_df
url = 'https://www.reddit.com/r/UIUC/comments/4ir5qs/easiest_2_or_3_hour_classes_hopefully_updated_for/'

In [3]:
subreddit_scraper(url)

             name points        time
0         CeigeCJ      0  1 year ago
1         CeigeCJ      0  1 year ago
2    speedster217      1  1 year ago
3       aleale913      2  1 year ago
4     Astasieusol      1  1 year ago
5       aleale913      1  1 year ago
6     Astasieusol      1  1 year ago
7          vox000      1  1 year ago
8     theillini19      6  1 year ago
9   AccountTaken1      5  1 year ago
10     Hippocoons      4  1 year ago
11      jimbogobo      3  1 year ago
12        prozran      2  1 year ago
13        prozran      2  1 year ago
14      RCoombs77      2  1 year ago
15   speedster217      2  1 year ago
16      aleale913      1  1 year ago
17      bubba5590      1  1 year ago
18        logane7      1  1 year ago
19      10twenty4      1  1 year ago
20       poketape      1  1 year ago
21      aprilfols      0  1 year ago
22      ericred22      7  1 year ago
23      ECEPerson      3  1 year ago